# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "encryption_cli",
    "decrypter",
    "encrypter",
    "file",
    "keys",
]

[workspace.dependencies]
rsa = "0.7.2"
rand = "0.8.5"
